const chatbotData = [
  { q: "What is Hillwood Manor?", a: "Hillwood Manor is a newly renovated apartment community located at 1732 Stone St, Union City, TN, offering comfortable 1, 2, and 3-bedroom apartments." },
  { q: "Where is Hillwood Manor located?", a: "We are located at 1732 Stone St, Union City, Tennessee 38261." },
  { q: "What types of apartments do you offer?", a: "We offer 1-bedroom, 2-bedroom, and 3-bedroom apartments." },
  { q: "What is the starting rent?", a: "Rent starts from $950 per month for selected floor plans." },
  { q: "Do you have one-bedroom apartments?", a: "Yes. Our Pleasant Valley floor plan is a 1-bedroom, 1-bath apartment with approximately 648 sq ft." },
  { q: "Do you have two-bedroom apartments?", a: "Yes. Our Stone Street floor plan includes 2 bedrooms, 1 bathroom, and approximately 850 sq ft." },
  { q: "Do you have three-bedroom apartments?", a: "Yes. Our Obion floor plan offers 3 bedrooms, 2 bathrooms, and approximately 1,150 sq ft." },
  { q: "How much does the one-bedroom apartment cost?", a: "The one-bedroom apartment starts at $950 per month." },
  { q: "How much does the two-bedroom apartment cost?", a: "The two-bedroom apartment starts at $1,050 per month." },
  { q: "How much is the three-bedroom apartment?", a: "Please contact our leasing office for current pricing." },
  { q: "Are the apartments newly renovated?", a: "Yes. Our apartments feature updated flooring, fresh paint, and modern fixtures." },
  { q: "Are pets allowed?", a: "Yes. Hillwood Manor is a pet-friendly community." },
  { q: "Is there a pet fee?", a: "Yes. A non-refundable pet fee and monthly pet rent apply." },
  { q: "Are there breed restrictions?", a: "Yes. Breed restrictions and weight limits may apply." },
  { q: "Does the property have a swimming pool?", a: "Yes. Residents enjoy access to a community swimming pool." },
  { q: "Is parking available?", a: "Yes. Off-street resident parking is available." },
  { q: "Is laundry available?", a: "Yes. We have on-site laundry facilities." },
  { q: "Is emergency maintenance available?", a: "Yes. We offer 24-hour emergency maintenance." },
  { q: "Do apartments have air conditioning?", a: "Yes. Every apartment includes central air conditioning and heating." },
  { q: "Are closets large?", a: "Yes. Our apartments feature spacious closets." },
  { q: "Is the neighborhood quiet?", a: "Yes. Hillwood Manor is located on a peaceful residential street." },
  { q: "What city is Hillwood Manor in?", a: "Union City, Tennessee." },
  { q: "What zip code is the property located in?", a: "38261." },
  { q: "Can I schedule a tour?", a: "Yes. You can schedule a tour by contacting our leasing office." },
  { q: "How do I contact the leasing office?", a: "Call us at 731-599-1049." },
  { q: "What is your phone number?", a: "Our leasing office can be reached at 731-599-1049." },
  { q: "What are your office hours?", a: "Office hours vary. Please call ahead before visiting." },
  { q: "How do I apply?", a: "Please contact our leasing office or submit an inquiry through our contact form." },
  { q: "Is parking free?", a: "Resident parking is available. Contact us for parking details." },
  { q: "Are apartments family friendly?", a: "Yes. Our community is suitable for individuals, couples, and families." },
  { q: "Is there a playground?", a: "Yes. Our community includes outdoor recreational spaces." },
  { q: "Is there green space?", a: "Yes. Hillwood Manor features mature trees and green open areas." },
  { q: "What shopping is nearby?", a: "Walmart Supercenter, Food Giant, and Tractor Supply are just minutes away." },
  { q: "Is Walmart nearby?", a: "Yes. Walmart Supercenter is approximately 1.2 miles away." },
  { q: "Are restaurants nearby?", a: "Yes. Several restaurants and coffee shops are nearby." },
  { q: "Is Higher Ground Coffee nearby?", a: "Yes. It's approximately 1 mile away." },
  { q: "Is Snappy Tomato Pizza nearby?", a: "Yes. It's about 0.9 miles away." },
  { q: "Is Tyson Foods nearby?", a: "Yes. Tyson Foods is approximately 3.5 miles away." },
  { q: "Is Baptist Memorial Hospital nearby?", a: "Yes. The hospital is about 2.1 miles away." },
  { q: "Are schools nearby?", a: "Yes. Union City Schools are approximately 1.8 miles away." },
  { q: "What amenities are included?", a: "Renovated interiors, pool, laundry facilities, parking, green spaces, and emergency maintenance." },
  { q: "Do apartments have large windows?", a: "Yes. Large windows provide plenty of natural light." },
  { q: "Are floor plans open?", a: "Yes. Our apartments feature open layouts." },
  { q: "Are apartments spacious?", a: "Yes. Apartments range from approximately 648 to 1,150 square feet." },
  { q: "What is the largest apartment?", a: "The Obion floor plan at approximately 1,150 sq ft." },
  { q: "Which apartment is best for couples?", a: "Our Pleasant Valley one-bedroom is ideal for couples." },
  { q: "Which apartment is best for roommates?", a: "The Stone Street two-bedroom is perfect for roommates." },
  { q: "Which apartment is best for families?", a: "The Obion three-bedroom is designed for families." },
  { q: "Are apartments modern?", a: "Yes. They feature updated interiors with modern finishes." },
  { q: "Are apartments move-in ready?", a: "Yes. Our renovated apartments are ready for new residents." },
  { q: "Can I send a message online?", a: "Yes. Use the contact form on our Contact page." },
  { q: "How do I request availability?", a: "Contact the leasing office by phone or submit the inquiry form." },
  { q: "Is pricing guaranteed?", a: "Pricing and availability are subject to change." },
  { q: "Do you have maintenance staff?", a: "Yes, including 24-hour emergency maintenance." },
  { q: "Is Hillwood Manor safe?", a: "We strive to provide a peaceful residential community." },
  { q: "Are apartments renovated?", a: "Yes, recently renovated." },
  { q: "Do apartments include heating?", a: "Yes." },
  { q: "Do apartments include air conditioning?", a: "Yes." },
  { q: "How many bathrooms does the one-bedroom have?", a: "One bathroom." },
  { q: "How many bathrooms does the three-bedroom have?", a: "Two bathrooms." },
  { q: "Can I bring my dog?", a: "Yes, subject to pet policy." },
  { q: "Can I bring my cat?", a: "Yes." },
  { q: "Is pet rent required?", a: "Yes." },
  { q: "Is there a security deposit?", a: "Please contact the leasing office for current deposit information." },
  { q: "What is included in rent?", a: "Please contact the leasing office for details." },
  { q: "Are dimensions exact?", a: "Floor plan sizes are approximate." },
  { q: "How early should I apply?", a: "We recommend applying as soon as possible." },
  { q: "Is there a waiting list?", a: "Contact the leasing office for current availability." },
  { q: "Are utilities included?", a: "Please contact the leasing office." },
  { q: "Can I schedule a viewing today?", a: "Call 731-599-1049 to check availability." },
  { q: "Where can I park?", a: "Resident parking is available on-site." },
  { q: "Do apartments have natural light?", a: "Yes." },
  { q: "Are closets walk-in?", a: "Apartments feature generous closet space." },
  { q: "Is internet included?", a: "Contact the leasing office." },
  { q: "Is there storage?", a: "Some floor plans include extra storage." },
  { q: "What is the Pleasant Valley floor plan?", a: "A 1-bedroom apartment with approximately 648 sq ft." },
  { q: "What is the Stone Street floor plan?", a: "A 2-bedroom apartment with approximately 850 sq ft." },
  { q: "What is the Obion floor plan?", a: "A 3-bedroom apartment with approximately 1,150 sq ft." },
  { q: "Is the community professionally managed?", a: "Yes." },
  { q: "Do you have mature trees?", a: "Yes." },
  { q: "Is there landscaping?", a: "Yes." },
  { q: "Can I visit without an appointment?", a: "Please call ahead since office hours vary." },
  { q: "Do you have a leasing office?", a: "Yes." },
  { q: "What county are you located in?", a: "Obion County." },
  { q: "What nearby employers are there?", a: "Tyson Foods and Baptist Memorial Hospital." },
  { q: "Is the property near downtown?", a: "It is conveniently located near shopping and dining." },
  { q: "Do apartments have updated flooring?", a: "Yes." },
  { q: "Do apartments have modern fixtures?", a: "Yes." },
  { q: "Are apartments freshly painted?", a: "Yes." },
  { q: "Is the community peaceful?", a: "Yes." },
  { q: "How can I get directions?", a: "Visit our Contact page or use your preferred navigation app with our address." },
  { q: "Do you accept online inquiries?", a: "Yes." },
  { q: "How can I check apartment availability?", a: "Contact our leasing office." },
  { q: "Can I speak with a leasing agent?", a: "Yes." },
  { q: "What makes Hillwood Manor unique?", a: "Newly renovated apartments, spacious layouts, a quiet neighborhood, and responsive maintenance." },
  { q: "Are tours free?", a: "Yes." },
  { q: "Can families live here?", a: "Absolutely." },
  { q: "Is Hillwood Manor close to grocery stores?", a: "Yes." },
  { q: "Why should I choose Hillwood Manor?", a: "We offer renovated apartments, spacious floor plans, excellent amenities, and a convenient Union City location." },
  { q: "I still have questions.", a: "We'd be happy to help! Call our leasing office at 731-599-1049 or send us a message through the Contact page, and our team will assist you." }
];
